name: dart_s3_upload
description: A simple, convenient package for uploading to S3.
version: 2.5.0
homepage: none
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^3.6.0
  http: ^1.1.0
  recase: ^4.1.0
  optionals:
    git: git@github.com:MinkTec/dart_optionals.git
  mink_utils:
    git: git@github.com:MinkTec/mink_utils.git
