name: dart_s3_upload
description: A simple, convenient package for uploading to S3.
version: 2.5.0
homepage: none
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^1.0.3
  http: ^0.13.3
  recase: ^4.1.0
  optionals:
    git: https://github.com/MinkTec/dart_optionals
